// 선수 데이터베이스 (쉽게 추가/수정 가능하도록 분리된 파일)
// - officialId: 화면에 표시될 대소문자가 정확한 아이디
// - team: Team logos 폴더 안에 있는 로고 이미지 파일명 (팀이 없으면 "none" 으로 입력)
// - eventTeam: 연합팀이나 스폰서 팀 로고. 닉네임 뒤에 숫자 '2'를 붙였을 때(예: maru2) 이 로고가 뜹니다. 없으면 "" 로 비워두세요.
// - realName: 한국 선수의 실명 (외국인은 "" 로 비워두세요)
// - race: Icons 폴더에 있는 종족 이미지 (예: Icons/terran.png)
// - raceSC1: 스타1(SC:Evo)에서 주종이 다른 경우에만 추가 (예: Icons/protoss.png). 없으면 race와 동일하게 취급
// - flag: Flags 폴더에 있는 국기 이미지 (예: Flags/flag_kr.png)

window.PLAYER_DB = {
  "babymarine": { officialId: "BabyMarine", team: "Team logos/StreamerZone.png", eventTeam: "", realName: "", race: "Icons/terran.png", flag: "" },
  "bunny": { officialId: "Bunny", team: "Team logos/Team Liquid.png", eventTeam: "", realName: "", race: "Icons/terran.png", flag: "" },
  "byun": { officialId: "ByuN", team: "Team logos/Shopify Rebellion.png", eventTeam: "", realName: "변현우", race: "Icons/terran.png", flag: "Flags/flag_kr.png" },
  "classic": { officialId: "Classic", team: "Team logos/Virtus.Pro.png", eventTeam: "Team logos/턱돌호범.png", realName: "김도우", race: "Icons/protoss.png", flag: "Flags/flag_kr.png" },
  "clem": { officialId: "Clem", team: "Team logos/Team Liquid.png", eventTeam: "", realName: "", race: "Icons/terran.png", flag: "Flags/flag_fr.png" },
  "crank": { officialId: "Crank", team: "Team logos/ONSYDE.png", eventTeam: "", realName: "최재원", race: "Icons/protoss.png", flag: "Flags/flag_kr.png" },
  "creator": { officialId: "Creator", team: "none", eventTeam: "Team logos/지면 크랭크탓.png", realName: "장현우", race: "Icons/protoss.png", flag: "Flags/flag_kr.png" },
  "cure": { officialId: "Cure", team: "Team logos/Team Liquid.png", eventTeam: "", realName: "김도욱", race: "Icons/terran.png", flag: "Flags/flag_kr.png" },
  "dark": { officialId: "Dark", team: "none", eventTeam: "", realName: "박령우", race: "Icons/zerg.png", flag: "Flags/flag_kr.png" },
  "gerald": { officialId: "Gerald", team: "Team logos/StreamerZone.png", eventTeam: "", realName: "", race: "Icons/protoss.png", flag: "" },
  "ggmachine": { officialId: "GgMaChine", team: "Team logos/StalnieBalls.png", eventTeam: "", realName: "", race: "Icons/zerg.png", flag: "Flags/flag_ru.png" },
  "gumiho": { officialId: "GuMiho", team: "none", eventTeam: "", realName: "고병재", race: "Icons/terran.png", flag: "Flags/flag_kr.png" },
  "harstem": { officialId: "Harstem", team: "Team logos/Shopify Rebellion.png", eventTeam: "", realName: "", race: "Icons/protoss.png", flag: "Flags/flag_nl.png" },
  "hero": { officialId: "herO", team: "Team logos/T1.png", eventTeam: "Team logos/턱돌호범.png", realName: "김준호", race: "Icons/protoss.png", flag: "Flags/flag_kr.png" },
  "heromarine": { officialId: "HeroMarine", team: "none", eventTeam: "", realName: "", race: "Icons/terran.png", flag: "Flags/flag_de.png" },
  "jumy": { officialId: "Jumy", team: "Team logos/StreamerZone.png", eventTeam: "", realName: "", race: "Icons/protoss.png", flag: "" },
  "krystianer": { officialId: "Krystianer", team: "Team logos/ONSYDE.png", eventTeam: "", realName: "", race: "Icons/protoss.png", flag: "Flags/flag_pl.png" },
  "lambo": { officialId: "Lambo", team: "Team logos/Shopify Rebellion.png", eventTeam: "", realName: "", race: "Icons/zerg.png", flag: "Flags/flag_de.png" },
  "mana": { officialId: "MaNa", team: "Team logos/Team Liquid.png", eventTeam: "", realName: "", race: "Icons/protoss.png", flag: "" },
  "maru": { officialId: "Maru", team: "Team logos/ONSYDE.png", eventTeam: "", realName: "조성주", race: "Icons/terran.png", flag: "Flags/flag_kr.png" },
  "maxpax": { officialId: "MaxPax", team: "Team logos/PSISTORM Gaming.png", eventTeam: "", realName: "", race: "Icons/protoss.png", flag: "Flags/flag_dk.png" },
  "milkicow": { officialId: "MilkiCow", team: "Team logos/StalnieBalls.png", eventTeam: "", realName: "", race: "Icons/terran.png", flag: "Flags/flag_ru.png" },
  "neeb": { officialId: "Neeb", team: "Team logos/ONSYDE.png", eventTeam: "", realName: "", race: "Icons/protoss.png", flag: "Flags/flag_us.png" },
  "nicoract": { officialId: "Nicoract", team: "none", eventTeam: "", realName: "", race: "Icons/terran.png", flag: "Flags/flag_non.png" },
  "nightmare": { officialId: "NightMare", team: "Team logos/StreamerZone.png", eventTeam: "", realName: "장욱", race: "Icons/protoss.png", flag: "Flags/flag_kr.png" },
  "oliveira": { officialId: "Oliveira", team: "none", eventTeam: "", realName: "", race: "Icons/terran.png", flag: "Flags/flag_cn.png" },
  "percival": { officialId: "Percival", team: "none", eventTeam: "Team logos/지면 크랭크탓.png", realName: "정재영", race: "Icons/terran.png", flag: "Flags/flag_kr.png" },
  "rex": { officialId: "Rex", team: "Team logos/ONSYDE.png", eventTeam: "", realName: "", race: "Icons/zerg.png", flag: "Flags/flag_cn.png" },
  "reynor": { officialId: "Reynor", team: "Team logos/BASILISK.png", eventTeam: "", realName: "", race: "Icons/zerg.png", flag: "Flags/flag_it.png" },
  "rogue": { officialId: "Rogue", team: "none", eventTeam: "Team logos/지면 크랭크탓.png", realName: "이병렬", race: "Icons/zerg.png", flag: "Flags/flag_kr.png" },
  "ryung": { officialId: "Ryung", team: "Team logos/ONSYDE.png", eventTeam: "", realName: "김동원", race: "Icons/terran.png", flag: "Flags/flag_kr.png" },
  "scarlett": { officialId: "Scarlett", team: "Team logos/Shopify Rebellion.png", eventTeam: "", realName: "", race: "Icons/zerg.png", raceSC1: "Icons/protoss.png", flag: "Flags/flag_ca.png" },
  "serral": { officialId: "Serral", team: "Team logos/BASILISK.png", eventTeam: "", realName: "", race: "Icons/zerg.png", flag: "Flags/flag_fi.png" },
  "shameless": { officialId: "Shameless", team: "Team logos/StalnieBalls.png", eventTeam: "", realName: "", race: "Icons/protoss.png", flag: "Flags/flag_ru.png" },
  "shin": { officialId: "SHIN", team: "Team logos/ONSYDE.png", eventTeam: "Team logos/턱돌호범.png", realName: "신희범", race: "Icons/zerg.png", flag: "Flags/flag_kr.png" },
  "showtime": { officialId: "ShoWTimE", team: "none", eventTeam: "", realName: "", race: "Icons/protoss.png", flag: "Flags/flag_de.png" },
  "skillous": { officialId: "SKillous", team: "Team logos/Team Liquid.png", eventTeam: "", realName: "", race: "Icons/protoss.png", flag: "Flags/flag_non.png" },
  "solar": { officialId: "Solar", team: "none", eventTeam: "Team logos/턱돌호범.png", realName: "강민수", race: "Icons/zerg.png", flag: "Flags/flag_kr.png" },
  "sos": { officialId: "sOs", team: "Team logos/StreamerZone.png", eventTeam: "Team logos/지면 크랭크탓.png", realName: "김유진", race: "Icons/protoss.png", flag: "Flags/flag_kr.png" },
  "strange": { officialId: "Strange", team: "Team logos/StalnieBalls.png", eventTeam: "", realName: "", race: "Icons/protoss.png", flag: "Flags/flag_ru.png" },
  "trap": { officialId: "Trap", team: "none", eventTeam: "Team logos/지면 크랭크탓.png", realName: "조성호", race: "Icons/protoss.png", flag: "Flags/flag_kr.png" },
  "trigger": { officialId: "trigger", team: "Team logos/BASILISK.png", eventTeam: "", realName: "", race: "Icons/protoss.png", flag: "Flags/flag_ca.png" },
  "youngyakov": { officialId: "YoungYakov", team: "Team logos/StalnieBalls.png", eventTeam: "", realName: "", race: "Icons/zerg.png", flag: "Flags/flag_ru.png" },
  "zardient": { officialId: "ZaRDieNT", team: "Team logos/StalnieBalls.png", eventTeam: "", realName: "", race: "Icons/terran.png", flag: "Flags/flag_ru.png" },
  "zoun": { officialId: "Zoun", team: "Team logos/ONSYDE.png", eventTeam: "", realName: "박한솔", race: "Icons/protoss.png", flag: "Flags/flag_kr.png" },
  "blask": { officialId: "Blask", team: "none", eventTeam: "Team logos/Team RWB.png", realName: "", race: "Icons/protoss.png", raceSC1: "Icons/zerg.png", flag: "Flags/flag_hr.png" },
  "goblin": { officialId: "goblin", team: "none", eventTeam: "Team logos/Team RWB.png", realName: "", race: "Icons/protoss.png", flag: "Flags/flag_hr.png" },
  "uthermal": { officialId: "uThermal", team: "none", eventTeam: "Team logos/Team RWB.png", realName: "", race: "Icons/terran.png", flag: "Flags/flag_nl.png" },
  "vaeda": { officialId: "Vaeda", team: "none", eventTeam: "Team logos/Team RWB.png", realName: "", race: "Icons/protoss.png", flag: "Flags/flag_nl.png" },
  "innovation": { officialId: "INnoVation", team: "none", eventTeam: "", realName: "이신형", race: "Icons/terran.png", flag: "Flags/flag_kr.png" },
  "ty": { officialId: "TY", team: "none", eventTeam: "", realName: "전태양", race: "Icons/terran.png", flag: "Flags/flag_kr.png" },
  "fantasy": { officialId: "FanTaSy", team: "none", eventTeam: "", realName: "정명훈", race: "Icons/terran.png", flag: "Flags/flag_kr.png" },
  "soo": { officialId: "soO", team: "none", eventTeam: "", realName: "어윤수", race: "Icons/zerg.png", flag: "Flags/flag_kr.png" },
  "rebellion": { officialId: "ReBellioN", team: "none", eventTeam: "", realName: "강정우", race: "Icons/protoss.png", flag: "Flags/flag_kr.png" },
  "threepoint": { officialId: "threepoint", team: "none", eventTeam: "", realName: "정예준", race: "Icons/zerg.png", flag: "Flags/flag_kr.png" },
  "elazer": { officialId: "Elazer", team: "none", eventTeam: "Team logos/Team Liquid.png", realName: "", race: "Icons/zerg.png", flag: "Flags/flag_pl.png" }
};
